# Generated by Django 5.1.2 on 2024-11-04 05:22

import apps.workshop.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کارگاه')),
                ('photo', models.ImageField(upload_to=apps.workshop.models.upload_workshop_image, verbose_name='تصویر اصلی')),
                ('date', models.DateTimeField(verbose_name='تاریخ و زمان برگزاری')),
                ('place', models.CharField(max_length=50, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=80, verbose_name='مدرس')),
                ('information', models.TextField(verbose_name='اطلاعات')),
                ('registeration', models.TextField(verbose_name='شرایط ثبت نام')),
                ('report_text', models.TextField(blank=True, null=True, verbose_name='متن گزارش')),
                ('view_number', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال / غیر فعال')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد وضعیت')),
                ('status_title', models.CharField(max_length=50, verbose_name='عنوان وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.workshop.models.upload_gallery_image, verbose_name='تصویر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='کارگاه')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopstatus', verbose_name='وضعیت کارگاه'),
        ),
    ]
