# Generated by Django 5.1.2 on 2024-11-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'کارگاه', 'verbose_name_plural': 'کارگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='workshopgallery',
            options={'verbose_name': 'تصویر کارگاه', 'verbose_name_plural': 'تصاویر کارگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='workshopstatus',
            options={'verbose_name': 'وضعیت کارگاه', 'verbose_name_plural': 'وضعیت کارگاه ها'},
        ),
    ]
