# Generated by Django 5.1.2 on 2024-10-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('title_message', models.CharField(max_length=50, verbose_name='موضوع پیغام')),
                ('text', models.TextField(verbose_name='متن پیغام')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت پیام')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت مشاهده پیغام')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان مکان')),
                ('photo', models.ImageField(upload_to='media/images/place/', verbose_name='تصویر اصلی')),
                ('visiting_day', models.CharField(max_length=100, verbose_name='روز بازدید')),
                ('visiting_hours', models.CharField(max_length=100, verbose_name='ساعت بازدید')),
                ('rules', models.TextField(max_length=500, verbose_name='قوانین و مقررات')),
                ('more', models.TextField(max_length=3000, verbose_name='اطلاعات بیشتر')),
                ('place_registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت مکان')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
            },
        ),
        migrations.CreateModel(
            name='VisitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان گروه')),
            ],
            options={
                'verbose_name': 'عنوان گروه',
                'verbose_name_plural': 'عنوان گروه ها',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('place_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.place', verbose_name='مکان بازدید')),
                ('visitor_Group_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.visitorgroup', verbose_name='کد گروه بازدید کننده')),
            ],
            options={
                'verbose_name': 'بلیت',
                'verbose_name_plural': 'بلیت ها',
            },
        ),
    ]
