# Generated by Django 5.1.2 on 2024-10-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(upload_to='images/place/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='ticketprice',
            name='visitor_Group_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduction.visitorgroup', verbose_name='گروه بازدید کننده'),
        ),
    ]
