# Generated by Django 5.1.2 on 2024-10-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0002_alter_place_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rules',
            field=models.TextField(verbose_name='قوانین و مقررات'),
        ),
    ]
