# Generated by Django 5.1.2 on 2024-11-17 09:47

import apps.memory.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خاطره')),
                ('memory_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ خاطره')),
                ('text', models.TextField(verbose_name='متن خاطره')),
                ('photo', models.ImageField(upload_to=apps.memory.models.uploadimage, verbose_name='تصویر اصلی')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت خاطره')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.memory.models.uploadimage, verbose_name='تصویر')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_gallery', to='memory.memory', verbose_name='خاطره')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_like', to='memory.memory', verbose_name='خاطره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
