# Generated by Django 5.1.2 on 2024-10-26 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('photo', models.ImageField(upload_to='images/blog/', verbose_name='تصویر اصلی')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
                ('short_text', models.CharField(max_length=1000, verbose_name='متن خلاصه')),
                ('text', models.TextField(verbose_name='متن مقاله')),
                ('keywords', models.CharField(max_length=100, verbose_name='کلمات کلیدی')),
                ('pdf_name', models.CharField(max_length=200, verbose_name='نام فایل پی دی اف مقاله')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت مقاله')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار مقاله')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('visit', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان گروه')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه های مقاله',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('education', models.CharField(max_length=50, verbose_name='تحصیلات')),
                ('job', models.CharField(max_length=40, verbose_name='شغل')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
                ('number', models.IntegerField(max_length=11, verbose_name='شماره موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200, verbose_name='نام تصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'گالری مقاله',
                'verbose_name_plural': 'گالری مقاله ها',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articlegroup', verbose_name='عنوان گروه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='blog.author', verbose_name='نویسنده'),
        ),
    ]
