# Generated by Django 5.1.2 on 2024-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='articles', to='blog.author', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=1000, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/blog/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='photo_name',
            field=models.ImageField(upload_to='images/blog/gallery/', verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='author',
            name='number',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
    ]
